#!/usr/bin/env python

from __future__ import print_function

import sys, os

base = os.path.dirname(os.path.dirname(os.path.abspath(sys.argv[0])))
rtems = os.path.join(base, 'share', 'rtems')
sys.path = sys.path[0:1] + [rtems, base] + sys.path[1:]

try:
    import misc.tools.style
    misc.tools.style.run()
except ImportError:
    print("Incorrect RTEMS Tools installation", file = sys.stderr)
    sys.exit(1)
